// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.InteropServices

[<assembly: AssemblyTitleAttribute("Sojobo")>]
[<assembly: AssemblyProductAttribute("Sojobo")>]
[<assembly: GuidAttribute("274BAD77-1F86-4CBC-A5B6-1FF724940C53")>]
[<assembly: AssemblyCompanyAttribute("Enkomio")>]
[<assembly: AssemblyDescriptionAttribute("A binary analysis framework.")>]
[<assembly: AssemblyVersionAttribute("1.2.493.11")>]
[<assembly: AssemblyFileVersionAttribute("1.2.493.11")>]
[<assembly: AssemblyInformationalVersionAttribute("1.2.493.11")>]
[<assembly: AssemblyMetadataAttribute("BuildDate","2020-08-10")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Sojobo"
    let [<Literal>] AssemblyProduct = "Sojobo"
    let [<Literal>] Guid = "274BAD77-1F86-4CBC-A5B6-1FF724940C53"
    let [<Literal>] AssemblyCompany = "Enkomio"
    let [<Literal>] AssemblyDescription = "A binary analysis framework."
    let [<Literal>] AssemblyVersion = "1.2.493.11"
    let [<Literal>] AssemblyFileVersion = "1.2.493.11"
    let [<Literal>] AssemblyInformationalVersion = "1.2.493.11"
    let [<Literal>] AssemblyMetadata_BuildDate = "2020-08-10"
